//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tc.Assets {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tc.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Annul filters.
        /// </summary>
        public static string AnnulFiltersButton_Text {
            get {
                return ResourceManager.GetString("AnnulFiltersButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete entry.
        /// </summary>
        public static string DeleteEntryText {
            get {
                return ResourceManager.GetString("DeleteEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Must be not blank, length &lt; 64.
        /// </summary>
        public static string EntryAttribute_CustomTitle_ValidationMessage {
            get {
                return ResourceManager.GetString("EntryAttribute_CustomTitle_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completition Date.
        /// </summary>
        public static string EntryAttribute_DateCompleted {
            get {
                return ResourceManager.GetString("EntryAttribute_DateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Release Date.
        /// </summary>
        public static string EntryAttribute_DateRelease {
            get {
                return ResourceManager.GetString("EntryAttribute_DateRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на h..
        /// </summary>
        public static string EntryAttribute_Hours {
            get {
                return ResourceManager.GetString("EntryAttribute_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Must be non-negative.
        /// </summary>
        public static string EntryAttribute_Hours_ValidationMessage {
            get {
                return ResourceManager.GetString("EntryAttribute_Hours_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m..
        /// </summary>
        public static string EntryAttribute_Minutes {
            get {
                return ResourceManager.GetString("EntryAttribute_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на must be between 0 and 59.
        /// </summary>
        public static string EntryAttribute_Minutes_ValidationMessage {
            get {
                return ResourceManager.GetString("EntryAttribute_Minutes_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note.
        /// </summary>
        public static string EntryAttribute_Note {
            get {
                return ResourceManager.GetString("EntryAttribute_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length is limited to 512 characters.
        /// </summary>
        public static string EntryAttribute_Note_ValidationMessage {
            get {
                return ResourceManager.GetString("EntryAttribute_Note_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Score.
        /// </summary>
        public static string EntryAttribute_Score {
            get {
                return ResourceManager.GetString("EntryAttribute_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string EntryAttribute_Status {
            get {
                return ResourceManager.GetString("EntryAttribute_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string EntryAttribute_Time {
            get {
                return ResourceManager.GetString("EntryAttribute_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backlog.
        /// </summary>
        public static string EntryStatus_Backlog {
            get {
                return ResourceManager.GetString("EntryStatus_Backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completed.
        /// </summary>
        public static string EntryStatus_Completed {
            get {
                return ResourceManager.GetString("EntryStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In progress.
        /// </summary>
        public static string EntryStatus_InProgress {
            get {
                return ResourceManager.GetString("EntryStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retired.
        /// </summary>
        public static string EntryStatus_Retired {
            get {
                return ResourceManager.GetString("EntryStatus_Retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List.
        /// </summary>
        public static string GamesPage_TabList_Name {
            get {
                return ResourceManager.GetString("GamesPage_TabList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string GamesPage_TabSearch_Name {
            get {
                return ResourceManager.GetString("GamesPage_TabSearch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stats.
        /// </summary>
        public static string GamesPage_TabStats_Name {
            get {
                return ResourceManager.GetString("GamesPage_TabStats_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid username or password.
        /// </summary>
        public static string LoginPage_InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("LoginPage_InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string LoginPage_LoginButton {
            get {
                return ResourceManager.GetString("LoginPage_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string LoginPageHeader {
            get {
                return ResourceManager.GetString("LoginPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No completition date.
        /// </summary>
        public static string NoDateCompleted_Label {
            get {
                return ResourceManager.GetString("NoDateCompleted_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No date release.
        /// </summary>
        public static string NoDateRelease_Label {
            get {
                return ResourceManager.GetString("NoDateRelease_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No score.
        /// </summary>
        public static string NoScore_Label {
            get {
                return ResourceManager.GetString("NoScore_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Films.
        /// </summary>
        public static string PaneItem_FilmsPage {
            get {
                return ResourceManager.GetString("PaneItem_FilmsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Games.
        /// </summary>
        public static string PaneItem_GamesPage {
            get {
                return ResourceManager.GetString("PaneItem_GamesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string PaneItem_HomePage {
            get {
                return ResourceManager.GetString("PaneItem_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes.
        /// </summary>
        public static string SaveChangesText {
            get {
                return ResourceManager.GetString("SaveChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error encountered while performing request. Check your connection or try again later..
        /// </summary>
        public static string ServiceUnavableMessage {
            get {
                return ResourceManager.GetString("ServiceUnavableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort by.
        /// </summary>
        public static string SortBy_Label {
            get {
                return ResourceManager.GetString("SortBy_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completition Date.
        /// </summary>
        public static string SortByOption_DateCompletition {
            get {
                return ResourceManager.GetString("SortByOption_DateCompletition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Release date.
        /// </summary>
        public static string SortByOption_DateRelease {
            get {
                return ResourceManager.GetString("SortByOption_DateRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Score.
        /// </summary>
        public static string SortByOption_Score {
            get {
                return ResourceManager.GetString("SortByOption_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string SortByOption_Status {
            get {
                return ResourceManager.GetString("SortByOption_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string SortByOption_Time {
            get {
                return ResourceManager.GetString("SortByOption_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string SortByOption_Title {
            get {
                return ResourceManager.GetString("SortByOption_Title", resourceCulture);
            }
        }
    }
}
